FROM rocker/verse

RUN R -e "install.packages(c( \
    'tidyverse', \
    'janitor', \
    'cluster', \
    'rdist', \
    'RSpectra', \
    'plotly', \
    'Rtsne', \
    'patchwork', \
    'factoextra' \
), repos='https://cran.rstudio.com/')"